maintainer        "Glenn Prtt"
maintainer_email  "glenn@allplayers.com"
license           "Apache 2.0"
description       "Installs webgrind PHP profile visualization tool."
version           "0.1"
recipe            "webgrind::default", "Installs webgrind"
