cp -r ../cookbooks/apache2 .
cp -r ../cookbooks/apt .
cp -r ../cookbooks/build-essential .
cp -r ../cookbooks/imagemagick .
cp -r ../cookbooks/memcached .
cp -r ../cookbooks/mysql .
cp -r ../cookbooks/openssl .
cp -r ../cookbooks/php .
cp -r ../cookbooks/varnish .
